spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: order
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/bkeuty-order}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:yasuo20gg}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "order-service-group"

      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.bkeuty.*"
        spring:
          json:
            type:
              mapping: "com.bkeuty.product.dto.user.order.DecreaseStockStatusDto:com.bkeuty.order.dto.order.DecreaseStockStatusDto,com.bkeuty.shipping_service.dto.CreateShippingResponseMessage:com.bkeuty.order.dto.shipping.CreateShippingResponseMessage, com.bkeuty.shipping_service.dto.GhnWebhookDto:com.bkeuty.order.dto.shipping.GhnWebhookMessage"

  cloud:
    function:
      definition: uppercase
    function.web.path: /uppercase
  cloudinary:
    cloud-name: ${CLOUDINARY_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
  #  cloud-name: dyzcl7cbe
  #  api-key: 643964737283187
  #  api-secret: W4zCsQq3qscuxqFWUpW3es4rQMs
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    enabled: ${EUREKA_ENABLED:true}

springdoc:
  api-docs:
    path: /api/order/v3/api-docs

sepay:
  api-key: ${SEPAY_API_KEY:9DKDHVTKR4JGQFNIFXLO2NEZMHMSTVKDNIQTTQJ9DRQ0BLPUM4HPEEYHXVIVP5G5}
  account-number: SEPQUANG210804
  bank: OCB
  template: compact

ghn:
  api-token: ${GHN_API_TOKEN:7e4ff493-2f3f-11f1-a973-aee5264794df}
  return-phone: "0898680945"
  return-address: "4/21, đường 15, khu phố 3"
  from-district-id: 3695
  from-ward-code: "90740"
  shop-id: "199833"

service-base-url:
  auth-service: ${AUTH_SERVICE_URL:http://auth-service}
  product-service: ${PRODUCT_SERVICE_URL:http://product}
  shipping-service: ${SHIPPING_SERVICE_URL:http://shipping-service}
  payment-service: ${PAYMENT_SERVICE_URL:http://payment-service}
  user-service: ${USER_SERVICE_URL:http://user-service}
  promotion-service: ${PROMOTION_SERVICE_URL:http://promotion-service}

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:bkeuty-bucket}
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY_ID:AKIAWMSQIVJWHCVKCYVW}
    secret-key: ${AWS_SECRET_ACCESS_KEY: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}
    refund-evidence-folder: refund-evident