spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: lb://product
              predicates:
                - Path= /api/product/**,/api/category/**, /api/admin/product/**, /api/admin/category/**
              filters:
                - RemoveResponseHeader=Access-Control-Allow-Origin
                - RemoveResponseHeader=Access-Control-Allow-Methods
                - RemoveResponseHeader=Access-Control-Allow-Headers
                - RemoveResponseHeader=Access-Control-Allow-Credentials

            - id: order-service
              uri: lb://order
              predicates:
                - Path= /api/order/**,/api/cart/**, /api/admin/order/**,/api/admin/cart/**
              filters:
                - RemoveResponseHeader=Access-Control-Allow-Origin
                - RemoveResponseHeader=Access-Control-Allow-Methods
                - RemoveResponseHeader=Access-Control-Allow-Headers
                - RemoveResponseHeader=Access-Control-Allow-Credentials
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path= /api/auth/**
              filters:
                - RemoveResponseHeader=Access-Control-Allow-Origin
                - RemoveResponseHeader=Access-Control-Allow-Methods
                - RemoveResponseHeader=Access-Control-Allow-Headers
                - RemoveResponseHeader=Access-Control-Allow-Credentials
            - id: promotion-service
              uri: lb://promotion-service
              predicates:
                - Path= /api/promotion/**, /api/admin/promotion/**
              filters:
                - RemoveResponseHeader=Access-Control-Allow-Origin
                - RemoveResponseHeader=Access-Control-Allow-Methods
                - RemoveResponseHeader=Access-Control-Allow-Headers
                - RemoveResponseHeader=Access-Control-Allow-Credentials
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path= /api/user/**
              filters:
                - RemoveResponseHeader=Access-Control-Allow-Origin
                - RemoveResponseHeader=Access-Control-Allow-Methods
                - RemoveResponseHeader=Access-Control-Allow-Headers
                - RemoveResponseHeader=Access-Control-Allow-Credentials
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Product Service
        url: /api/product/v3/api-docs
      - name: Order Service
        url: /api/order/v3/api-docs
      - name: Auth Service
        url: /api/auth/v3/api-docs
      - name: User Service
        url: /api/user/v3/api-docs
      - name: Promotion Service
        url: /api/promotion/v3/api-docs

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO

server:
  port: 8080

