spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "shipping-service-group"
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.bkeuty.*"
        spring:
          json:
            type:
              mapping: "com.bkeuty.order.dto.order.ProcessRefundEventDto:com.bkeuty.user_service.dto.refund.ProcessRefundEventDto"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: ${EUREKA_ENABLED:true}
server:
  port: 8086

springdoc:
  api-docs:
    path: /api/user/v3/api-docs
keycloak:
  server-url: ${KEYCLOAK_BASE_URL:http://localhost:8181}
  issuer: ${KEYCLOAK_ISSUER:http://localhost:8181/realms/bkeuty}
  realm: ${REALM:bkeuty}
  client-id: ${CLIENT_ID:bkeuty-user-service}
  client-secret: ${CLIENT_SECRET:BVTdsuPlcW7Y8hDvO1xfgEWf1s063FQ1}

service-base-url:
  auth-service: ${AUTH_SERVICE_URL:http://auth-service}
