spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8086

springdoc:
  api-docs:
    path: /api/user/v3/api-docs
keycloak:
  server-url: http://localhost:8181
  issuer: http://localhost:8181/realms/bkeuty
  realm: bkeuty
  client-id: bkeuty-user-service
  client-secret: BVTdsuPlcW7Y8hDvO1xfgEWf1s063FQ1