spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: ${EUREKA_ENABLED:true}
server:
  port: 8086

springdoc:
  api-docs:
    path: /api/user/v3/api-docs
keycloak:
  server-url: ${KEYCLOAK_BASE_URL:http://localhost:8181}
  issuer: ${KEYCLOAK_ISSUER:http://localhost:8181/realms/bkeuty}
  realm: ${REALM:bkeuty}
  client-id: ${CLIENT_ID:bkeuty-user-service}
  client-secret: ${CLIENT_SECRET:BVTdsuPlcW7Y8hDvO1xfgEWf1s063FQ1}

service-base-url:
  auth-service: ${AUTH_SERVICE_URL:http://auth-service}
