spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: review-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/bkeuty-review}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:yasuo20gg}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8085

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /api/review/v3/api-docs
service-base-url:
  auth-service: ${AUTH_SERVICE_URL:http://auth-service}
  product-service: ${PRODUCT_SERVICE_URL:http://product}
  user-service: ${USER_SERVICE_URL:http://user-service}
  order-service: ${ORDER_SERVICE_URL:http://order}

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:bkeuty-bucket}
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
    review-images-folder: review-images